name: 'Build Plugin'
description: "Builds the Plugin"

runs:
  using: "composite"
  steps:

    - name: Start Docker
      shell: bash
      run: |
        docker run --rm --name shop --env NODE_VERSION=18 --env PHP_VERSION=8.1 -d dockware/dev:6.5.6.1
        sleep 20
        docker logs shop

    - name: Update Shopware Config
      shell: bash
      run: |
        docker exec shop bash -c 'sed -i "s/APP_ENV=dev/APP_ENV=prod/g" /var/www/html/.env' || true;

    - name: Upload into Docker
      shell: bash
      run: |
        docker cp $(pwd)/. shop:/var/www/html/custom/plugins/MolliePayments
        docker exec shop bash -c 'sudo chown www-data:www-data /var/www/html/custom/plugins -R'

    # --------------------------------------------------------------------------------------------------------------------------------------

    - name: Install Plugin
      shell: bash
      run: |
        docker exec shop bash -c 'cd /var/www/html/custom/plugins/MolliePayments && make prod'
        docker exec shop bash -c 'cd /var/www/html && php bin/console plugin:refresh'
        docker exec shop bash -c 'cd /var/www/html && php bin/console plugin:install MolliePayments --activate'
        docker exec shop bash -c 'cd /var/www/html && php bin/console cache:clear'

    - name: Build Plugin
      shell: bash
      run: |
        docker exec shop bash -c 'cd /var/www/html/custom/plugins/MolliePayments && make release'

    # --------------------------------------------------------------------------------------------------------------------------------------

    - name: Download ZIP File
      shell: bash
      run: |
        docker cp shop:/var/www/html/custom/plugins/.build/MolliePayments.zip ~/.build/MolliePayments.zip

    - name: Extract ZIP file for artifact
      shell: bash
      run: |
        unzip ~/.build/MolliePayments.zip -d ~/.build/MolliePayments

    - name: Store ZIP file in Github
      uses: actions/upload-artifact@v2
      with:
        name: MolliePayments-Shopware
        retention-days: 4
        path: ~/.build/MolliePayments

    - name: Delete TMP files
      shell: bash
      run: |
        rm -rf ~/.build/MolliePayments
