name: Build ZIP File

on:
  workflow_dispatch:

jobs:

  build:
    name: Build Plugin
    runs-on: ubuntu-latest
    steps:

      - name: Clone Code
        uses: actions/checkout@v3

      - name: Create Cache Directories
        run: |
          mkdir -p ~/.build

      - name: Mount Build Cache
        uses: actions/cache@v3
        with:
          key: cache-plugin-${{ github.run_id }}
          path: ~/.build

      - name: Build Plugin
        uses: ./.github/actions/build-plugin
