name: Step Review

on:
  workflow_call:
    inputs:
      PHP_VERSION:
        description: "PHP Version"
        required: true
        type: string

jobs:

  # ------------------------------------------------------------------------------------------------------------------------

  install_dev:
    name: Install Dev Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # -----------------------------------
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.PHP_VERSION }}
        # -----------------------------------
      - name: Mount Cache
        uses: actions/cache@v3
        with:
          key: cache-dev-dependencies-${{ github.run_id }}
          path: |
            node_modules
            vendor
            src/Resources/app/storefront/node_modules
            src/Resources/app/administration/node_modules
        # -----------------------------------
      - name: Install Dependencies
        run: make dev -B

  # ------------------------------------------------------------------------------------------------------------------------
  # ------------------------------------------------------------------------------------------------------------------------

  config:
    name: Test Plugin Configuration
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.PHP_VERSION }}

      - name: Test configuration
        run: make configcheck -B

  # ------------------------------------------------------------------------------------------------------------------------
  # ------------------------------------------------------------------------------------------------------------------------

  phpunuhi:
    name: Test Snippets
    runs-on: ubuntu-latest
    needs: install_dev
    steps:
      - name: Clone Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.PHP_VERSION }}

      - name: Mount Dev Dependency Cache
        uses: actions/cache@v3
        with:
          key: cache-dev-dependencies-${{ github.run_id }}
          path: |
            node_modules
            vendor
            src/Resources/app/storefront/node_modules
            src/Resources/app/administration/node_modules

      - name: Test snippets
        run: make phpunuhi -B

  vitest:
    name: Vitest Tests
    needs: install_dev
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        uses: actions/checkout@v3

      - name: Mount Dev Dependency Cache
        uses: actions/cache@v3
        with:
          key: cache-dev-dependencies-${{ github.run_id }}
          path: |
            node_modules
            vendor
            src/Resources/app/storefront/node_modules
            src/Resources/app/administration/node_modules

      - name: Run Vitest
        run: make vitest -B

  eslint:
    name: ESLint
    needs: install_dev
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        uses: actions/checkout@v3

      - name: Mount Dev Dependency Cache
        uses: actions/cache@v3
        with:
          key: cache-dev-dependencies-${{ github.run_id }}
          path: |
            node_modules
            vendor
            src/Resources/app/storefront/node_modules
            src/Resources/app/administration/node_modules

      - name: Run ESLint
        run: make eslint -B

  stylelint:
    name: Stylelint
    needs: install_dev
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        uses: actions/checkout@v3

      - name: Mount Dev Dependency Cache
        uses: actions/cache@v3
        with:
          key: cache-dev-dependencies-${{ github.run_id }}
          path: |
            node_modules
            vendor
            src/Resources/app/storefront/node_modules
            src/Resources/app/administration/node_modules

      - name: Run Stylelint
        run: make stylelint -B

  prettier:
    name: Prettier
    needs: install_dev
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        uses: actions/checkout@v3

      - name: Mount Dev Dependency Cache
        uses: actions/cache@v3
        with:
          key: cache-dev-dependencies-${{ github.run_id }}
          path: |
            node_modules
            vendor
            src/Resources/app/storefront/node_modules
            src/Resources/app/administration/node_modules

      - name: Run Prettier
        run: make prettier -B

# ------------------------------------------------------------------------------------------------------------------------
# ------------------------------------------------------------------------------------------------------------------------

  php_checks:
    name: PHP Syntax Checks
    needs: install_dev
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.PHP_VERSION }}

      - name: PHP Syntax Checks
        run: make phpcheck -B

  php_min:
    name: PHP ${{ inputs.PHP_VERSION }} Compatibility
    needs: install_dev
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.PHP_VERSION }}

      - name: Mount Dev Dependency Cache
        uses: actions/cache@v3
        with:
          key: cache-dev-dependencies-${{ github.run_id }}
          path: |
            node_modules
            vendor
            src/Resources/app/storefront/node_modules
            src/Resources/app/administration/node_modules

      - name: PHP Compatibility Checks
        run: make phpmin -B

  phpunit:
    name: PHPUnit
    needs: install_dev
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.PHP_VERSION }}

      - name: Mount Dev Dependency Cache
        uses: actions/cache@v3
        with:
          key: cache-dev-dependencies-${{ github.run_id }}
          path: |
            node_modules
            vendor
            src/Resources/app/storefront/node_modules
            src/Resources/app/administration/node_modules

      - name: Run PHPUnit
        run: make phpunit -B

  phpstan:
    name: PHPStan
    needs: install_dev
    runs-on: ubuntu-latest
    steps:

      - name: Clone Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.PHP_VERSION }}

      - name: Mount Dev Dependency Cache
        uses: actions/cache@v3
        with:
          key: cache-dev-dependencies-${{ github.run_id }}
          path: |
            node_modules
            vendor
            src/Resources/app/storefront/node_modules
            src/Resources/app/administration/node_modules

      - name: Run PHPStan
        run: make stan -B

  phpcsfixer:
    name: PHP CS Fixer
    needs: install_dev
    runs-on: ubuntu-latest
    steps:

      - name: Clone Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.PHP_VERSION }}

      - name: Mount Dev Dependency Cache
        uses: actions/cache@v3
        with:
          key: cache-dev-dependencies-${{ github.run_id }}
          path: |
            node_modules
            vendor
            src/Resources/app/storefront/node_modules
            src/Resources/app/administration/node_modules

      - name: Run PHP CS Fixer
        run: make csfix -B


